# Generated by Django 5.2 on 2025-04-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_comment_donation_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
