# Generated by Django 5.2 on 2025-04-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='donated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
