# Generated by Django 5.2 on 2025-04-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_user_report_reporter_remove_report_content_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment'), ('fraud', 'Fraud'), ('copyright', 'Copyright Violation'), ('offensive', 'Offensive Content'), ('hate_speech', 'Hate Speech'), ('false_information', 'False Information'), ('other', 'Other')], max_length=20),
        ),
    ]
